"""add leetcode_url to problems

Revision ID: 62b844328cc6
Revises: d42aa5b20376
Create Date: 2026-08-28 12:20:45.873608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b844328cc6'
down_revision: Union[str, Sequence[str], None] = 'd42aa5b20376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_problems_user_problem')
    )
    op.create_index(op.f('ix_user_problems_id'), 'user_problems', ['id'], unique=False)
    op.add_column('problems', sa.Column('leetcode_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_problems_leetcode_url'), 'problems', ['leetcode_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_leetcode_url'), table_name='problems')
    op.drop_column('problems', 'leetcode_url')
    op.drop_index(op.f('ix_user_problems_id'), table_name='user_problems')
    op.drop_table('user_problems')
    # ### end Alembic commands ###
