"""add progress table

Revision ID: 818c27c1bab4
Revises: a606b5257f89
Create Date: 2026-08-26 15:32:12.671503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818c27c1bab4'
down_revision: Union[str, Sequence[str], None] = 'a606b5257f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progress', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progress', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_progress_user_problem', 'progress', ['user_id', 'problem_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_progress_user_problem', 'progress', type_='unique')
    op.alter_column('progress', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('progress', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
